---
abstract: 'A smarter readability score'
author:
  - 'Brandon Singer <bsinger@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-Clarity
no_index:
  directory:
    - t
    - inc
requires:
  Lingua::EN::Sentence: 0
  Lingua::EN::Syllable: 0
  Math::Round: 0
  Test::More: 0
version: 0.01
